name: CI
on: [push]

jobs:
  tests:
    name: 'Automated tests'
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v1
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.14.0
      - name: Install dependencies
        run: yarn
      - name: Build projects
        run: yarn build
      - name: Run automated tests
        run: yarn test
        env:
          CI: true
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          file: packages/*/*/coverage/clover.xml
          fail_ci_if_error: false
